const primaryColors = require("./primary_colors");
module.exports = {
  purge: [
    "./src/**/*.{php,html,js,jsx,ts,tsx,vue}",
    "./public/**/*.{php,html,js,jsx,ts,tsx,vue}",
    "./resources/**/*.{php,html,js,jsx,ts,tsx,vue}",
    "./node_modules/@left4code/tw-starter/**/*.js",
  ],
  darkMode: "class",
  theme: {
    borderColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: primaryColors.gray["200"],
    }),
    extend: {
      fontFamily: {
        rubik: ["Rubik"],
        roboto: ["Roboto"],
      },
      colors: {
        ...primaryColors,
        theme: {
          1: "#312c7d",
          2: "#F1F5F8",
          3: "#3d369b",
          4: "#463eb1",
          5: "#DEE7EF",
          6: "#D32929",
          7: "#365A74",
          8: "#D2DFEA",
          9: "#91C714",
          10: "#3d369b",
          11: "#F78B00",
          12: "#FBC500",
          13: "#7F9EB9",
          14: "#E6F3FF",
          15: "#8DA9BE",
          16: "#607F96",
          17: "#FFEFD9",
          18: "#D8F8BC",
          19: "#312c7d",
          20: "#3d369b",
          21: "#C6D4FD",
          22: "#E8EEFF",
          23: "#312c7d",
          24: "#3d369b",
          25: "#C7D2FF",
          26: "#262261",
          27: "#312c7d",
          28: "#BBC8FD",
          29: "#463eb1",
          30: "#98AFF5",
        },
      },
      container: {
        center: true,
      },
      maxWidth: {
        "1/4": "25%",
        "1/2": "50%",
        "3/4": "75%",
      },
      screens: {
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        xxl: "1600px",
      },
      strokeWidth: {
        0.5: 0.5,
        1.5: 1.5,
        2.5: 2.5,
      },
    },
  },
  variants: {
    extend: {
      zIndex: ["responsive", "hover"],
      position: ["responsive", "hover"],
      padding: ["responsive", "last"],
      margin: ["responsive", "last"],
      borderWidth: ["responsive", "last"],
      backgroundColor: ["last", "first", "odd", "responsive", "hover", "dark"],
      borderColor: ["last", "first", "odd", "responsive", "hover", "dark"],
      textColor: ["last", "first", "odd", "responsive", "hover", "dark"],
      boxShadow: ["last", "first", "odd", "responsive", "hover", "dark"],
      borderOpacity: ["last", "first", "odd", "responsive", "hover", "dark"],
      backgroundOpacity: [
        "last",
        "first",
        "odd",
        "responsive",
        "hover",
        "dark",
      ],
    },
  },
};
