import { Form } from "@/components/master-form/types/form";

export const editAssociation: Form = {
  submitButtonText: "Save Association",
  editButtonText: "Edit Association",
  submitButtonClass: "right-align-submit",
  groups: [
    {
      title: "Association Information",
      fields: [
        {
          title: "Name",
          label: "Name",
          name: "name",
          type: "text",
          isRequired: true,
          description: "Enter name",
          validationMessage: "Please enter name",
          span: 12,
          value: "",
        },
        {
          title: "Description",
          label: "Description",
          name: "description",
          type: "text",
          isRequired: true,
          description: "Enter Description",
          validationMessage: "Please enter Description",
          span: 12,
          value: "",
        },
        {
          title: "Address",
          label: "Address",
          name: "address",
          type: "text",
          isRequired: true,
          description: "Enter address",
          validationMessage: "Please enter address",
          span: 12,
          value: "",
        },
        {
          title: "Phone",
          label: "Phone",
          name: "phone",
          type: "text",
          isRequired: true,
          description: "Enter phone",
          validationMessage: "Please enter phone",
          span: 6,
          value: "",
        },
        {
          title: "Email",
          label: "Email",
          name: "email",
          type: "text",
          isRequired: true,
          description: "Enter email",
          validationMessage: "Please enter email",
          span: 6,
          value: "",
        },
        {
          title: "Ward",
          label: "Ward",
          name: "ward",
          type: "text",
          isRequired: true,
          description: "Enter ward",
          validationMessage: "Please enter ward",
          span: 6,
          value: "",
        },
        {
          title: "Village",
          label: "Village",
          name: "description",
          type: "text",
          isRequired: true,
          description: "Enter village",
          validationMessage: "Please enter village",
          span: 6,
          value: "",
        },
        {
          title: "District",
          label: "District",
          name: "district",
          type: "text",
          isRequired: true,
          description: "Enter district",
          validationMessage: "Please enter district",
          span: 6,
          value: "",
        },
        {
          title: "Region",
          label: "Region",
          name: "region",
          type: "text",
          isRequired: true,
          description: "Enter region",
          validationMessage: "Please enter region",
          span: 6,
          value: "",
        },
        {
          title: "Quantity Threshold",
          label: "Quantity Threshold",
          name: "quantityThreshold",
          type: "text",
          isRequired: true,
          description: "Enter Quantity Threshold",
          validationMessage: "Please enter Quantity Threshold",
          span: 12,
          value: "",
        },
      ],
    },
  ],
};
